final_project/django/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    # home/
    # 로그아웃 전용 홈페이지
    path('', views.logged_out_list, name='logged_out_list'),

    # home/category/1
    # 로그인 전용 홈페이지
    path('category/<int:category_id>/', views.category_view, name='category'),

    #home/1/activity_management/
    path('activity_management/', views.activity_management, name='activity_management'),

]

final_project/django/ksc_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('news/', include('news.urls')),
    path('home/', include('home.urls')),
]

final_project/django/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # 기사 페이지 domain/news/1/
    path('<int:article_id>/', views.news_detail, name="news_detail"),

    # 기사 페이지 댓글 작성 기능  domain/news/1/artcle-comment-create-function/
    path('<int:article_id>/artcle-comment-create-function/', views.news_comment_create, name="news_comment_create"),

    # 기사 북마크 (좋아요) 처리 기능  domain/news/1/bookmarked-fuction/
    path("<int:article_id>/bookmarked-fuction/", views.news_bookmarked, name="news_bookmarked"),
    
    # 기사 평점 기능  domain/news/1/rating-function/
    path("<int:article_id>/rating-function/", views.news_rating, name="news_rating"),
    
    # 북마크 목록 news/1/bookmark_list
    path("<int:user_pk>/bookmark_list/", views.bookmark_list, name="bookmark_list"),  

    # 북마크 삭제 news/bookmark_delete/1
    path('bookmark_delete/<int:bookmark_id>/', views.bookmark_delete, name='bookmark_delete'),
   
    # 댓글 목록 news/1/comment_list
    path("<int:user_pk>/comment_list/", views.comment_list, name="comment_list"),  

    # 댓글 삭제 news/comment_delete/1
    path('comment_delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

final_project/django/home/models.py
from django.db import models
from django.conf import settings 


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name



class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    abstract = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content_url = models.URLField()
    article_public_Date = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} 가 {self.article.title} 기사에 남긴 댓글"

class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} 가 {self.article.title} 기사를 북마크함"

class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ratings_choices = [
        (0.5, 0.5),
        (1.0, 1.0),
        (1.5, 1.5),
        (2.0, 2.0),
        (2.5, 2.5),
        (3.0, 3.0),
        (3.5, 3.5),
        (4.0, 4.0),
        (4.5, 4.5),
        (5.0, 5.0)
    ]
    ratings = models.FloatField(choices=ratings_choices)

    def __str__(self):
        return f"{self.user}가 {self.article.title} 기사에 남긴 평점"


class User_Article_Bookmark_TB(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_age = models.IntegerField(verbose_name="나이")
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    abstract = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user_age} 연령의 {self.user}가 {self.article.title} 기사를 북마크"


class User_Article_Rating_TB(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_age = models.IntegerField(verbose_name="나이")
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ratings = models.FloatField()
    abstract = models.TextField()
    article_public_Date = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user_age} 연령의 {self.user}가 {self.article.title} 기사에 대한 평점"
        

class age_recommand_Article_TB(models.Model):
    age = models.IntegerField(verbose_name="나이")
    tag = models.TextField()

    def __str__(self):
        return f"연령대: {self.age}, Tag: {self.tag}"

final_project/django/home/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from account.models import Users_info
from django.db.models import Avg
from django.contrib.auth.models import User
from .models import Article, Category, Bookmark, Rating, User_Article_Rating_TB, User_Article_Bookmark_TB, age_recommand_Article_TB
from django.http import HttpResponse

import requests
import numpy as np
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from django_pandas.io import read_frame
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from .utils import timezone, filter_age_range, preprocess_and_extract_topics, extract_keywords, extract_words, recommend_similar_articles, user_custom_extract_topics, user_custom_recommendation_similar_articles, clean_text, generate_wordcloud_data
# nltk.download('stopwords')
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
stop_words = set(stopwords.words('english'))

# 자동
from django.views import View
import schedule
import time
import requests


# 워드클라우드 
from wordcloud import WordCloud   # pip install wordcloud
import matplotlib.pyplot as plt
import io
import base64



# 비회원 전용 홈페이지
@require_safe
def logged_out_list(request):
    # 최신 기사 6개
    latest_articles = Article.objects.all().order_by('-article_public_Date')[:6]

    context = {
        'latest_articles': latest_articles,
    }

    # 템플릿 렌더링
    return render(request, 'home/logged_out_index.html', context)



# 로그인 전용 홈페이지
@login_required
@require_safe
def category_view(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    category_articles = Article.objects.filter(category=category).order_by('-article_public_Date')
    categories = Category.objects.all()
    
    latest_articles = Article.objects.all().order_by('-article_public_Date')[:6]
    
    # 기사별 평균 평점 계산
    # 뻘짓 조심: 카테고리로 나눴다는 걸 생각을 안하고 있었음. 그래서 새로운 함수로 평점을 계산해도 템플릿은 {% for article in category_articles %}을 사용하기에 보여지지도 않았던 거였음..ㅠ
    for article in category_articles:
        article.average_rating = article.rating_set.aggregate(avg_rating=Avg('ratings'))['avg_rating']
    
    # 페이지네이션
    paginator = Paginator(category_articles, 10)  # 페이지당 10개의 기사를 보여줌
    page = request.GET.get('page')

    if page is None:
        page = 1
    else:   
        try:
            page = int(page)
        except ValueError:
            page = 1
    
    try:
        category_articles = paginator.page(page)
    except PageNotAnInteger:
        # 페이지가 정수가 아닌 경우, 첫 번째 페이지를 반환
        category_articles = paginator.page(1)
    except EmptyPage:
        # 페이지가 범위를 벗어난 경우, 마지막 페이지를 반환
        category_articles = paginator.page(paginator.num_pages)  

    leftIndex = (int(page) - 2) 
    if leftIndex < 1:
        leftIndex = 1

    rightIndex = (int(page) + 2)
    if rightIndex > paginator.num_pages:
        rightIndex = paginator.num_pages

    custom_range = range(leftIndex, rightIndex+1)

    # 유사 기사 추천
    age_recommand_articles = age_recommand_Article_TB.objects.all()
    # 최신기사 150개 유사도 분석
    new_articles = Article.objects.all().order_by('-article_public_Date')[:150]
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform([user_tag.tag for user_tag in age_recommand_articles])

    recommended_articles = recommend_similar_articles(age_recommand_articles, new_articles, tfidf_vectorizer, tfidf_matrix)
    

    # 워드클라우드 단어 리스트 
    recent_articles_for_word_cloud = Article.objects.filter(category_id=category_id).order_by('-article_public_Date')[:60]
    word_freq_dict = generate_wordcloud_data(recent_articles_for_word_cloud)

    # 워드클라우드 이미지 생성
    wordcloud= WordCloud(width=800, height=400, background_color='white').generate_from_frequencies(word_freq_dict)
    plt.figure(figsize=(8,4))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.tight_layout(pad=0)

    # 이미지를 바이트로 변환하여 임시 메모리에 저장
    image_stream = io.BytesIO()
    plt.savefig(image_stream, format='png')
    image_stream.seek(0)

    # 바이트로 변환된 이미지를 base64로 인코딩하여 HTML 에 직접 포함
    image_base64 = base64.b64encode(image_stream.getvalue()).decode()

    return render(
        request,
        "home/logged_index.html",
        {
            "category_name": category.name,  # 카테고리 이름을 템플릿으로 전달
            "category_articles": category_articles,
            "categories": categories,
            "latest_articles": latest_articles,
            "custom_range": custom_range,
            "recommended_articles": recommended_articles,
            "wordcloud_image": f"data:image/png;base64,{image_base64}",
        },
    )

# 활동관리 페이지
@login_required
@require_safe
def activity_management(request):
    return render(request, 'home/activity_management.html')


# 연령별 핵심토픽 업데이트
# 일주일에 한번 돌아가기
def process_data(request):
    # 연령대별 데이터프레임 생성
    age_ranges = [(10, 20), (20, 30), (30, 40), (40, 50), (50, 60)]
    age_df_list = [filter_age_range(User_Article_Rating_TB.objects.all(), age_range) for age_range in age_ranges]

    # 연령대별 가중치, 불용어처리 및 핵심 토픽 추출
    topics_age_list = []
    for age_df in age_df_list:
        result_age_df = preprocess_and_extract_topics(age_df)
        topics_age_df = extract_words(extract_keywords(result_age_df['processed_abstract']))
        topics_age_list.append(topics_age_df)

    # 데이터베이스에 저장
    for i, topics_age in enumerate(topics_age_list):
        # 연령대를 새로 추가할때
        age_instance, created = age_recommand_Article_TB.objects.get_or_create(age=10 * (i+1))
        # 기존 연령대의 tag만 업데이트
        if not created:  
            age_instance.tag = topics_age
            age_instance.save()

final_project/django/home/templates/home/activity_management.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1><strong>활동 관리</strong></h1>
            {% if user.is_authenticated %}
            <p>원하시는 버튼을 클릭하여 {{ user.username }}님이 작성하신 북마크 또는 댓글을 관리하세요:D</p>
            {% endif %}
            <div class="row justify-content-center align-items-center">
                <div class="col-md-6 text-center">
                    <a href="{% url 'news:bookmark_list' user_pk=user.pk %}" class="btn btn-outline-dark m-3">북마크 관리</a>
                </div>
                <div class="col-md-6 text-center">
                    <a href="{% url 'news:comment_list' user_pk=user.pk %}" class="btn btn-outline-dark m-3">댓글 관리</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

final_project/django/home/templates/home/index.html
{% extends 'base.html' %}

{% block page_title %}{{ category_name }}{% endblock page_title %}

{% block content %}

<div class="container mt-5 mb-5">
    <h1><strong>최신 기사 6개</strong></h1>
  
    <div class="row row-cols-1 row-cols-md-2 g-4">
      {% for article in latest_articles %}
      <div class="col">
        <div class="card h-100">
          <div class="card-body btn btn-outline-dark">
            <a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none; color: black;">
              <h5 class="card-title"><strong>{{ article.title }}</strong></h5>
              <p class="card-text"><strong>Category:</strong> {{ article.category.name }}</p>
              <p class="card-text"><strong>Date:</strong> {{ article.article_public_Date|slice:"5:10" }}</p>
              <p class="card-text">{{ article.abstract }}</p>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</div>

{% if user.is_authenticated %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mb-4"><strong>카테고리 목록</strong></h1>
            <div class="d-flex flex-wrap">
                {% for category in categories %}
                <a href="{% url 'home:category' category.id %}" class="btn btn-outline-dark m-2">{{ category.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="mb-4">{{ category_name }} News</h2>
            <ul class="list-group">
                {% for article in category_articles %}
                <li class="list-group-item">
                  <a href="{% url 'news:news_detail' article.id %}" class="text-decoration-none text-dark">{{ article.title }}</a>
                  <span class="float-end text-decoration-none text-dark"> |{{ article.article_public_Date|slice:"5:10"  }}</span>
                  <a class="float-end text-decoration-none text-dark">평점({{ article.average_rating|default:"-"|floatformat:2 }})| Bookmarked({{ article.bookmark_set.count }})</a>
                </li>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<div class="pagination justify-content-center mt-5 mb-5">
  <ul class="pagination custom-pagination">
    {% if category_articles.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">&laquo; 처음</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ category_articles.previous_page_number }}">이전</a>
      </li>
    {% endif %}

    {% for num in custom_range %}
      <li class="page-item {% if num == category_articles.number %}active{% endif %}">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
    {% endfor %}

    {% if category_articles.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ category_articles.next_page_number }}">다음</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ category_articles.paginator.num_pages }}">마지막 &raquo;</a>
      </li>
    {% endif %}
  </ul>
</div>

<div class="container mt-5 mb-5 text-center">
  <h2 class="mb-5"> <strong> 최근 60개 기사의 키워드입니다 :D </strong></h2>
  <img src="{{ wordcloud_image }}" alt="Word Cloud">
</div>


<div class="container mt-5">
  <div class="row justify-content-center">
  <h1 class="mb-4"><strong>연령대별 추천 기사</strong></h1>
  <h3 class="mb-4"><strong>지난 일주일간 연령별로 인기가 많은 기사에요! 확인해보세요:D</strong></h3>
  <div class="row">
    {% for age_group in recommended_articles %}
      <div class="col-md-2 mx-auto">
        {% if age_group.user_age < 20 %}
          <h2>10대</h2>
        {% elif age_group.user_age < 30 %}
        <h2>20대</h2>
        {% elif age_group.user_age < 40 %}
        <h2>30대</h2>
        {% elif age_group.user_age < 50 %}
        <h2>40대</h2>
        {% else %}
          <h2>50대</h2>
        {% endif %}
        <ul class="list-group">
          {% for article in age_group.articles %}
            <li class="list-group-item">
              <a href="{% url 'news:news_detail' article.id %}" class="text-decoration-none text-dark">{{ article.title }}</a>
              <p class="text-decoration-none text-dark">category: {{ article.category }}</p>
              <span class="float-end text-decoration-none text-dark"> |{{ article.article_public_Date|slice:"5:10"  }}</span>
            </li>
          {% endfor %}
        </ul>
      </div>
      {% endfor %}
    </div>
</div>




{% endblock content %}

final_project/django/home/templates/home/logged_index.html
{% extends 'base.html' %}

{% block page_title %}{{ category_name }}{% endblock page_title %}

{% block content %}


<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mb-4"><strong>카테고리 목록</strong></h1>
            <div class="d-flex flex-wrap">
                {% for category in categories %}
                <a href="{% url 'home:category' category.id %}" class="btn btn-outline-dark m-2">{{ category.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="mb-4">{{ category_name }} News</h2>
            <ul class="list-group">
                {% for article in category_articles %}
                <li class="list-group-item">
                  <a href="{% url 'news:news_detail' article.id %}" class="text-decoration-none text-dark">{{ article.title }}</a>
                  <span class="float-end text-decoration-none text-dark"> |{{ article.article_public_Date|slice:"5:10"  }}</span>
                  <a class="float-end text-decoration-none text-dark">평점({{ article.average_rating|default:"-"|floatformat:2 }})| Bookmarked({{ article.bookmark_set.count }})</a>
                </li>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<div class="pagination justify-content-center mt-5 mb-5">
  <ul class="pagination custom-pagination">
    {% if category_articles.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">&laquo; 처음</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ category_articles.previous_page_number }}">이전</a>
      </li>
    {% endif %}

    {% for num in custom_range %}
      <li class="page-item {% if num == category_articles.number %}active{% endif %}">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
    {% endfor %}

    {% if category_articles.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ category_articles.next_page_number }}">다음</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ category_articles.paginator.num_pages }}">마지막 &raquo;</a>
      </li>
    {% endif %}
  </ul>
</div>

<div class="container mt-5 mb-5 text-center">
  <h2 class="mb-5"> <strong> 최근 60개 기사의 키워드입니다 :D </strong></h2>
  <img src="{{ wordcloud_image }}" alt="Word Cloud">
</div>

<div class="container mt-5 mb-5">
  <h1><strong>최신 기사 6개</strong></h1>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for article in latest_articles %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body btn btn-outline-dark">
          <a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none; color: black;">
            <h5 class="card-title"><strong>{{ article.title }}</strong></h5>
            <p class="card-text"><strong>Category:</strong> {{ article.category.name }}</p>
            <p class="card-text"><strong>Date:</strong> {{ article.article_public_Date|slice:"5:10" }}</p>
            <p class="card-text">{{ article.abstract }}</p>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
  <h1 class="mb-4"><strong>연령대별 추천 기사</strong></h1>
  <h3 class="mb-4"><strong>지난 일주일 기사중 연령대별로 좋아할 만한 기사를 추천했어요! 확인해보세요:D</strong></h3>
  <div class="row">
    {% for age_group in recommended_articles %}
      <div class="col-md-2 mx-auto">
        {% if age_group.user_age < 20 %}
          <h2>10대</h2>
        {% elif age_group.user_age < 30 %}
          <h2>20대</h2>
        {% elif age_group.user_age < 40 %}
          <h2>30대</h2>
        {% elif age_group.user_age < 50 %}
          <h2>40대</h2>
        {% else %}
          <h2>50대</h2>
        {% endif %}
        <ul class="list-group">
          {% for article in age_group.articles %}
            <li class="list-group-item">
              <a href="{% url 'news:news_detail' article.id %}" class="text-decoration-none text-dark">{{ article.title }}</a>
              <p class="text-decoration-none text-dark">category: {{ article.category }}</p>
              <span class="float-end text-decoration-none text-dark"> |{{ article.article_public_Date|slice:"5:10"  }}</span>
            </li>
          {% endfor %}
        </ul>
      </div>
    {% endfor %}
  </div>
</div>



{% endblock content %}

final_project/django/home/templates/home/logged_out_index.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5 mb-5">
  <h1><strong>최신 기사 6개</strong></h1>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for article in latest_articles %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body btn btn-outline-dark">
          <a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none; color: black;">
            <h5 class="card-title"><strong>{{ article.title }}</strong></h5>
            <p class="card-text"><strong>Category:</strong> {{ article.category.name }}</p>
            <p class="card-text"><strong>Date:</strong> {{ article.article_public_Date|slice:"5:10" }}</p>
            <p class="card-text">{{ article.abstract }}</p>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock content %}