final_project/django/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    # home/
    # 로그아웃 전용 홈페이지
    path('', views.logged_out_list, name='logged_out_list'),

    # home/category/1
    # 로그인 전용 홈페이지
    path('category/<int:category_id>/', views.category_view, name='category'),

    #home/1/activity_management/
    path('activity_management/', views.activity_management, name='activity_management'),

]

final_project/django/ksc_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('news/', include('news.urls')),
    path('home/', include('home.urls')),
]

final_project/django/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # 기사 페이지 domain/news/1/
    path('<int:article_id>/', views.news_detail, name="news_detail"),

    # 기사 페이지 댓글 작성 기능  domain/news/1/artcle-comment-create-function/
    path('<int:article_id>/artcle-comment-create-function/', views.news_comment_create, name="news_comment_create"),

    # 기사 북마크 (좋아요) 처리 기능  domain/news/1/bookmarked-fuction/
    path("<int:article_id>/bookmarked-fuction/", views.news_bookmarked, name="news_bookmarked"),
    
    # 기사 평점 기능  domain/news/1/rating-function/
    path("<int:article_id>/rating-function/", views.news_rating, name="news_rating"),
    
    # 북마크 목록 news/1/bookmark_list
    path("<int:user_pk>/bookmark_list/", views.bookmark_list, name="bookmark_list"),  

    # 북마크 삭제 news/bookmark_delete/1
    path('bookmark_delete/<int:bookmark_id>/', views.bookmark_delete, name='bookmark_delete'),
   
    # 댓글 목록 news/1/comment_list
    path("<int:user_pk>/comment_list/", views.comment_list, name="comment_list"),  

    # 댓글 삭제 news/comment_delete/1
    path('comment_delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

final_project/django/home/models.py
from django.db import models
from django.conf import settings 


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name



class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    abstract = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content_url = models.URLField()
    article_public_Date = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} 가 {self.article.title} 기사에 남긴 댓글"

class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} 가 {self.article.title} 기사를 북마크함"

class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ratings_choices = [
        (0.5, 0.5),
        (1.0, 1.0),
        (1.5, 1.5),
        (2.0, 2.0),
        (2.5, 2.5),
        (3.0, 3.0),
        (3.5, 3.5),
        (4.0, 4.0),
        (4.5, 4.5),
        (5.0, 5.0)
    ]
    ratings = models.FloatField(choices=ratings_choices)

    def __str__(self):
        return f"{self.user}가 {self.article.title} 기사에 남긴 평점"


class User_Article_Bookmark_TB(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_age = models.IntegerField(verbose_name="나이")
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    abstract = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user_age} 연령의 {self.user}가 {self.article.title} 기사를 북마크"


class User_Article_Rating_TB(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_age = models.IntegerField(verbose_name="나이")
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ratings = models.FloatField()
    abstract = models.TextField()
    article_public_Date = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user_age} 연령의 {self.user}가 {self.article.title} 기사에 대한 평점"
        

class age_recommand_Article_TB(models.Model):
    age = models.IntegerField(verbose_name="나이")
    tag = models.TextField()

    def __str__(self):
        return f"연령대: {self.age}, Tag: {self.tag}"

final_project/django/news/forms.py
from django import forms 
from home.models import Comment, Rating

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', ]
        widgets = {
            'content' : forms.TextInput(
                attrs={
                    'placeholder' : '댓글 달기...', 
                }
            )
        }


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["ratings", ]
        widgets = {
            'ratings' : forms.Select(choices = Rating.ratings_choices)
        }

final_project/django/news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from home.models import Article, Comment, Bookmark, Rating, User_Article_Rating_TB, User_Article_Bookmark_TB
from account.models import Users_info

from news.forms import CommentForm, RatingForm
from django.urls import reverse
# Create your views here.
# def news_detail(request, article_pk):
#     article = get_object_or_404(Article, pk=article_pk)

# 뉴스 내용 보여주기
def news_detail(request, article_id):
    article = Article.objects.get(pk=article_id)
    comment_form = CommentForm()
    rating_form = RatingForm()
    is_bookmark = article.bookmark_set.filter(user=request.user.pk).exists()
    return render(request, "news/news_detail.html", {"article" : article,
                                                     "comment_form" : comment_form,
                                                     "rating_form" : rating_form,
                                                     "is_bookmark" : is_bookmark
                                                    })



# 댓글 작성 로직
@login_required
def news_comment_create(request, article_id):
    form = CommentForm(request.POST)
    article = get_object_or_404(Article, pk=article_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.article = article
        comment.save()
    return redirect("news:news_detail", article.pk)



# 북마크 생성 및 삭제 로직
@login_required
def news_bookmarked(request, article_id):
    if request.method == "POST":
        article = Article.objects.get(pk = article_id)
        user = request.user

        # 사용자가 북마크 누른 객체 가져오기
        bookmarked_article = user.bookmark_set.filter(article = article)
        bookmarked_article_user = user.user_article_bookmark_tb_set.filter(article=article)

        # 만약 사용자가 북마크 누른 기사가, 북마크 누른 기사 목록들에 있다면 삭제
        if bookmarked_article.exists():
            bookmarked_article.delete()
            if bookmarked_article_user.exists():
                bookmarked_article_user.delete()
        else:
            user.bookmark_set.create(user=user, article=article)

            # user_article_rating_tb
            user_info = user.users_info_set.first()  # 사용자 정보 가져오기
            if user_info:
                user_age = user_info.user_age  # 사용자의 나이 가져오기
            else:
                user_age = None  # 사용자 정보가 없는 경우 처리
            abstract = article.abstract
            category = article.category
            User_Article_Bookmark_TB.objects.create(user=user, user_age=user_age, article=article, abstract=abstract, category=category,  )


    return redirect("news:news_detail", article.pk)


# 평점
@login_required
def news_rating(request, article_id):
    if request.method == "POST":
        article = Article.objects.get(pk=article_id)
        user = request.user
        new_rate = float(request.POST.get("ratings"))  # 사용자가 선택한 새로운 평점 가져오기

        # 사용자가 해당 기사에 대해 이미 평가한 평점이 있는지 확인
        rated_article = user.rating_set.filter(article=article)
        rated_article_user = user.user_article_rating_tb_set.filter(article=article)

        # 만약 이미 평점이 존재한다면 업데이트
        if rated_article.exists():
            rated_article.update(ratings=new_rate)
            if rated_article_user.exists():
                rated_article_user.update(ratings=new_rate)
        else:
            # 새로운 평점 생성
            rating_instance = Rating.objects.create(user=user, article=article, ratings=new_rate)

            # User_Article_Rating_TB에도 동일한 평점 생성
            user_info = user.users_info_set.first()  # 사용자 정보 가져오기
            if user_info:
                user_age = user_info.user_age  # 사용자의 나이 가져오기
            else:
                user_age = None  # 사용자 정보가 없는 경우 처리
            abstract = article.abstract
            article_public_Date = article.article_public_Date
            User_Article_Rating_TB.objects.create(user=user, user_age=user_age, article=article, ratings=new_rate, abstract=abstract, article_public_Date=article_public_Date)

    return redirect("news:news_detail", article_id)


# 사용자별 북마크 리스트
@login_required
def bookmark_list(request, user_pk):
    # 현재 로그인한 사용자의 댓글 목록
    user_bookmarks = Bookmark.objects.filter(user=request.user)
    return render(request, 'news/bookmark_list.html', {'user_bookmarks': user_bookmarks})


# 북마크 삭제
@login_required
def bookmark_delete(request, bookmark_id):
    bookmark = get_object_or_404(Bookmark, id=bookmark_id)

    # 북마크 삭제하면 User_Article_Bookmark_TB에 있는 북마크 데이터도 삭제될수 있도록 하기
    User_Article_Bookmark_TB.objects.filter(article_id=bookmark.article.id, user_id=request.user.id).delete()
    
    # 북마크 삭제 처리
    bookmark.delete()
    
    # 북마크 삭제 후 댓글 리스트 페이지로 리디렉션
    return redirect(reverse('news:bookmark_list', kwargs={'user_pk': request.user.pk}))


# 사용자별 댓글 리스트
@login_required
def comment_list(request, user_pk):
    # 현재 로그인한 사용자의 댓글 목록
    user_comments = Comment.objects.filter(user=request.user)
    return render(request, 'news/comment_list.html', {'user_comments': user_comments})

# 댓글 삭제
@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    
    # 댓글 삭제 처리
    comment.delete()
    
    # 댓글 삭제 후 댓글 리스트 페이지로 리디렉션
    return redirect(reverse('news:comment_list', kwargs={'user_pk': request.user.pk}))

final_project/django/news/templates/news/bokmark_delete.html
{% extends "base.html" %}

{% block content %}

{% for bookmark in user.bookmarks.all %}
    <p>{{ bookmark.article.title }}</p>
    <form action="{% url 'delete_bookmark' bookmark.id %}" method="post">
        {% csrf_token %}
        <button type="submit">북마크 삭제</button>
    </form>
{% endfor %}

    
{% endblock %}

final_project/django/news/templates/news/bookmark_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body text-center">
          <h1>내가 저장한 기사</h1>

          <ul class="list-group list-group-flush">
            {% for bookmark in user_bookmarks %}
              <li class="list-group-item">
                <span class="float-start">{{ bookmark.article.title }}</span>
                <form method="post" action="{% url 'news:bookmark_delete' bookmark.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-sm float-end">삭제</button>
                  <a href="{% url 'news:news_detail' bookmark.article.id %}" class="btn btn-primary btn-sm float-end">기사 보기</a>
                </form>
              </li>
            {% empty %}
              <li class="list-group-item">저장한 기사가 없습니다.</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

final_project/django/news/templates/news/comment.html
<div>
    {% if request.user.is_authenticated %}

    <!-- 댓글 작성 칸 및 버튼 -->
    <form action="{% url "news:news_comment_create" article.pk %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="article" value="{{ article.pk }}">
        {{ comment_form.content }}
        <button type="submit" class="btn btn-secondary btn-sm">댓글 작성</button>
    </form>
</div>

<div>
    <ul class="list-group">
        <!-- 해당 기사 댓글 목록 보여주기 / 없으면 안내문 보여주기 -->
        {% for comment in article.comment_set.all  %}
        <li class="list-group-item"> {{ comment.content }} | <b>{{ comment.user  }}</b> </li>
        {% empty %}
        <li> 첫 댓글을 달아보세요 :D </li>   
        {% endfor %}
    </ul>
</div>
    {% else %}
        <strong> 다른회원들의 댓글, 평점, 북마크 수를 보고 싶으면 회원가입을 해주세요:D </strong>
{% endif %}

final_project/django/news/templates/news/comment_delete.html
{% extends "base.html" %}

{% block content %}

{% for comment in comments %}
    <div class="comment">
        <p>{{ comment.text }}</p>
        <form action="{% url 'delete_comment' comment.id %}" method="post">
            {% csrf_token %}
            <button type="submit">삭제</button>
        </form>
    </div>
{% endfor %}

    
{% endblock %}

final_project/django/news/templates/news/comment_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body text-center">
          <h1>내가 작성한 댓글 목록</h1>

          <ul class="list-group list-group-flush">
            {% for comment in user_comments %}
              <li class="list-group-item">
                <span class="float-start">[{{ comment.article.title }}] {{ comment.content }}</span>
                <form method="post" action="{% url 'news:comment_delete' comment.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-sm float-end">삭제</button>
                  <a href="{% url 'news:news_detail' comment.article.id %}" class="btn btn-primary btn-sm float-end">기사 보기</a>
                </form>
              </li>
            {% empty %}
              <li class="list-group-item">작성한 댓글이 없습니다.</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

final_project/django/news/templates/news/news_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-header">
                    <h2>{{ article.title }}</h2>
                </div>
                
                <div class="card-body">
                    <div class="card-text"><strong>Date:</strong> {{ article.article_public_Date|slice:"5:10" }}</div>
                    <div class="row-mt-5">
                        <strong>Category:</strong> {{ article.category }}
                    </div>
                    
                    <div class="row mt-5">
                        Comments({{ article.comment_set.count}}) | Bookmarked({{ article.bookmark_set.count }})
                    </div>
                    
                    {% if request.user.is_authenticated %}
                        <p>
                            <h3><strong>Abstract</strong></h3>
                        </p>
                        <div class="card-text mb-5">
                            {{ article.abstract }}
                        </div>
                        <hr class="my-2">

                        <p>
                            <h3><strong>Content</strong></h3>
                        </p>
                        <div class="card-text mb-5">
                            {{ article.content}}
                        </div>
                        <hr class="my-2">

                        <div class="card-text mb-5">
                            <a href="{{ article.content_url }}" target="_blank"> <stong>Want to see the original text? Click the url!</stong></a>
                        </div>
                    

                    {% else %}
                        <div class="card-text mb-5">
                            {{ article.content }}
                        </div>
                        <hr class="my-2">

                        <div class="card-text mb-5">
                            <a href="{{ article.content_url }}" target="_blank"> 원문 url </a>
                        </div>
                    {% endif %}


                    <!--  로그인 한 회원만 북마크, 댓글, 평점 기능 사용 가능-->
                    {% if request.user.is_authenticated %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <!-- 북마크 기능 -->
                                <!-- 만약 사용자가 인증되었다면, 북마크 버튼 나옴 -->
                                <div>
                                    <form action="{% url "news:news_bookmarked" article.pk %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" name="bookmark_action">
                                            {% if is_bookmark %}
                                                ❤️ Unbookmark
                                            {% else %}
                                                🤍 Bookmark
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                            </div>
                            
                            <div class="col-md-6">
                                <div>
                                    <!-- 평점 기능 -->
                                    <form action="{% url "news:news_rating" article.pk %}" method="POST">
                                        {% csrf_token %}
                                        {{ rating_form }}
                                        <button type="submit" class="btn btn-secondary btn-sm">평점 달기</button>
                                    </form>
                                </div>
                            </div>

                        </div>
                    {% endif %}

                        <div>
                            <!-- 댓글 창 및 기능-->
                            {% include "news/comment.html" %}
                        </div>

                </div>    
            </div>
        </div>
    </div>


{% endblock content %}