final_project/django/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    #account/signup/
    path('signup/', views.signup, name='signup'),

    #account/1/signup_info/
    path('<int:user_pk>/signup_info/', views.signup_info, name='signup_info'),

    #account/1/user_info/
    path('<int:user_pk>/user_info/', views.user_info, name='user_info'),

    #account/1/update_user_info/
    path('<int:user_pk>/update_user_info/', views.update_user_info, name='update_user_info'),

    # account/login/
    path('login/', views.login, name='login'),
 
    # account/logout/
    path('logout/', views.logout, name='logout'),

    # account/1/mypage/
    path('<int:user_pk>/mypage/', views.mypage_recomm_and_bookmark, name='mypage_recomm_and_bookmark'),

    # account/delete_account
    path('delete_account/', views.delete_account, name='delete_account'),
]

final_project/django/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    # home/
    # 로그아웃 전용 홈페이지
    path('', views.logged_out_list, name='logged_out_list'),

    # home/category/1
    # 로그인 전용 홈페이지
    path('category/<int:category_id>/', views.category_view, name='category'),

    #home/1/activity_management/
    path('activity_management/', views.activity_management, name='activity_management'),

]

final_project/django/ksc_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('news/', include('news.urls')),
    path('home/', include('home.urls')),
]

final_project/django/templates/base.html
<!-- base_nav.html -->
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>KSC</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <!-- 홈 버튼 이미지 -->
      <button id="homeButton" onclick="goHome()" style="border: none; background: none; padding: 0; margin: 0;">
        <img src="{% static 'img/logo2.png' %}" alt="Home Button" width="150" height="auto" style="border: none; display: block;">
      </button>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <script>
          function goHome() {
              window.location.href = "/home/category/1"; 
          }
          </script>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "account:mypage_recomm_and_bookmark" user_pk=user.pk %}">마이 페이지</a>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "home:activity_management"%}">활동 관리</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "account:user_info" user_pk=user.pk %}">개인 정보</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "account:logout" %}">로그아웃</a>
          </li>
          {% else %}
          <script>
          function goHome() {
            window.location.href = "/home"; 
          }
          </script>
          <div>
            <a href="{% url "account:login" %}" class="text-decoration-none text-dark mx-2">로그인</a>
            <a href="{% url "account:signup" %}" class="text-decoration-none text-dark mx-2">회원가입</a>
          </div>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}{% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>
</html>

final_project/django/templates/base_in.html
<!-- logged_nav.html -->
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>KSC</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      {% comment %} <a class="navbar-brand" href="{% url 'home:category' category_id=1 %}">KSC</a> {% endcomment %}
      <!-- 홈 버튼 이미지 -->
      <button id="homeButton" onclick="goHome()">
        <img src="{% static 'img/logo.png' %}" alt="Home Button" width="150" height="auto" style="border: none;">
      </button>

      <script>
      // JavaScript 코드
      function goHome() {
        window.location.href = "/home/category/1"; // 홈 페이지의 URL로 이동
      }
      </script>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "home:activity_management"%}">활동 관리</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "account:user_info" user_pk=user.pk %}">개인 정보</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "account:logout" %}">로그아웃</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}{% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>
</html>
  

final_project/django/templates/base_out.html
<!-- base_nav_logged_out.html -->
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>KSC</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
 <body> 
  <nav class="navbar d-flex justify-content-between">
    <div class="container-fluid">
      {% comment %} <a class="navbar-brand" href="{% url "home:logged_out_list" %}">KSC</a> {% endcomment %}
      <!-- 홈 버튼 이미지 -->
      <button id="homeButton" onclick="goHome()">
        <img src="{% static 'img/logo.png' %}" alt="Home Button" width="150" height="auto" style="border: none;">
      </button>

      <script>
      // JavaScript 코드
      function goHome() {
        window.location.href = "/home"; // 홈 페이지의 URL로 이동
      }
      </script>
      <div>
        <a href="{% url "account:login" %}" class="text-decoration-none text-dark mx-2">로그인</a>
        <a href="{% url "account:signup" %}" class="text-decoration-none text-dark mx-2">회원가입</a>
      </div>
    </div>
  </nav>
  {% block content %}{% endblock content %}    
</body>
</html>